---
- name: using blocks
  hosts: centos
  tasks:
    - name: intended to be successful
      block:
        - name: remove file
          command:
            cmd: rm /var/www/html/index.html
      rescue:
        - name: create file
          file:
            path: /tmp/rescuefile
            state: touch
      always:
        - name: always write message to logs
          command:
            cmd: /usr/bin/logger hello       
