---
- name: file copy modules
  hosts: test
  tasks:
  - name: copy file demo
    copy:
      src: /etc/hosts
      dest: /tmp/
  - name: add some lines to /tmp/hosts
    blockinfile:
      path: /tmp/hosts
      block: |
        192.168.200.100 host1.example.com
        192.168.100.101 host2.example.com
      state: present
  - name: verify file checksum
    stat:
      path: /tmp/hosts
      checksum_algorithm: md5
    register: result
  - debug: 
      msg: "The checksum of /tmp/hosts is {{ result.stat.checksum }}"
  - name: fetch the file
    fetch:
      src: /tmp/hosts
      dest: /tmp/      
