---
- name: set up web browser
  hosts: centos
  force_handlers: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
  - name: copy index html
    copy:
      src: /tmp/index.html
      dest: /var/www/html/index.html
    notify:
        - restart-web
  - name: copy nothing - intended to fail
    copy:
      src: /tmp/nothing
      dest: /var/www/html/nothing.html
  handlers:
    - name: restart-web
      service:
        name: httpd      
        state: restarted
