---
- name: install start and enable httpd
  gather_facts: false
  hosts: centos8-01
  tasks:
  - name: install package
    package:
      name: httpd
      state: latest
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: open firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes

- name: test https accessibility
  become: false
  gather_facts: false
  hosts: localhost
  tasks:
  - name: tets httpd access
    uri:
      url: http://centos8-01
