---
- name: start some services
  hosts: centos8-02
  vars:
    my_services:
      - crond
      - sshd
  tasks:
    - name: start some services
      service:
        name: "{{ item }}"
        state: started
      loop: "{{my_services}}"  
