---
- name: unnstall start and enable httpd
  gather_facts: false
  hosts: centos
  tasks:
  - name: unnstall package
    package:
      name: httpd
      state: absent

# - name: test https accessibility
#   become: false
#   gather_facts: false
#   hosts: localhost
#   tasks:
#   - name: tets httpd access
#     uri:
#       url: http://centos8-01
