---
- name: using variable include file
  hosts: centos
  gather_facts: no
  become: yes
  vars_files: myvars.yaml
  tasks:
  - name: install package {{ maypackage }}
    yum:
      name: "{{ mypackage }}"
      state: latest
