---
- name: using variable omclude file
  hosts: centos8-01
  gather_facts: no
  vars_files: myvars.yaml
  tasks:
  - name: install package {{ maypackage }}
    yum:
      name: "{{ mypackage }}"
      state: latest
