---
- name: Create user using variable
  hosts: centos
  become: yes
  vars:
    user: paul
  tasks:
    - name: create userr {{ user }} on host {{ ansible_hostname }} 
      user:
        name: "{{ user }}" 
