---
- name: vars_prompt demo
  hosts: localhost
  vars_prompt:
    - name: package
      prompt: which package to install?
      private: no
  tasks:
  - debug:
      msg: the package is {{ package }}

- name: additional play
  hosts: localhost
  tasks:
  - debug:
      msg: demonstrationg scope of {{ package }}         

